/*
 * CssSuite.java
 * JUnit based test
 *
 * Created on den 25 juli 2004, 13:10
 */

package net.homelinux.tobe.css;

import junit.framework.*;

/**
 *
 * @author Torbjörn Gannholm
 */
public class CssSuite extends TestCase {
    
    public CssSuite(java.lang.String testName) {
        super(testName);
    }
    
    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("CssSuite");
        suite.addTest(net.homelinux.tobe.css.StyleMapTest.suite());
        suite.addTest(net.homelinux.tobe.css.RulesetSelectorTest.suite());
        return suite;
    }
    
    // TODO add test methods here, they have to start with 'test' name.
    // for example:
    // public void testHello() {}
    
    
}
