/*
 * {{{ header & license
 * CssSuite.java
 * Copyright (c) 2004 Torbjörn Gannholm
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 * }}}
 */

package net.homelinux.tobe.css;

import junit.framework.*;

/**
 *
 * @author Torbjörn Gannholm
 */
public class CssSuite extends TestCase {
    
    public CssSuite(java.lang.String testName) {
        super(testName);
    }
    
    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("CssSuite");
        suite.addTest(net.homelinux.tobe.css.StyleMapTest.suite());
        suite.addTest(net.homelinux.tobe.css.RulesetSelectorTest.suite());
        return suite;
    }
    
    // TODO add test methods here, they have to start with 'test' name.
    // for example:
    // public void testHello() {}
    
    
}
