/*
 * CssSuite.java
 * Copyright (c) 2004 Torbjörn Gannholm
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * as published by the Free Software Foundation; either version 2.1
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 */

package org.xhtmlrenderer.css.match;

import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;


/**
 * @author   Torbjörn Gannholm
 */
public class CssSuite extends TestCase {

    /**
     * Constructor for the CssSuite object
     *
     * @param testName  PARAM
     */
    public CssSuite( java.lang.String testName ) {
        super( testName );
    }

    /**
     * suite method automatically generated by JUnit module
     *
     * @return   The test suite
     */
    public static Test suite() {
        TestSuite suite = new TestSuite( "CssSuite" );
        suite.addTest( StyleMapTest.suite() );
        suite.addTest( RulesetSelectorTest.suite() );
        return suite;
    }

    // TODO add test methods here, they have to start with 'test' name.
    // for example:
    // public void testHello() {}


}

/*
 * $Id$
 *
 * $Log$
 * Revision 1.3  2004/10/23 13:29:06  pdoubleya
 * Re-formatted using JavaStyle tool.
 * Cleaned imports to resolve wildcards except for common packages (java.io, java.util, etc).
 * Added CVS log comments at bottom.
 *
 *
 */

