define. fs Flying Saucer

define. css21 "CSS 2.1 Specification":http://www.w3.org/TR/CSS21/

define. itext "iText":http://www.lowagie.com/iText/

define. jlogging "java.util.logging":http://java.sun.com/j2se/1.4.2/docs/api/java/util/logging/package-summary.html

define. mailing-list.user "mailing list":https://xhtmlrenderer.dev.java.net/servlets/ProjectMailingListList

define. css base.css

define. style
#logo { float: left;
  }
.clearit { clear: both;
  }
h2 { width: 500px;
  }
ul#m2 { border: 1px solid black;
  float: right;
  }
block { border: 0px solid black;
  display: block;
  padding-left: 4em;
  }
.axial { border: 1px solid black; display: none;}
p.screenshot { text-align: center; }
p.screenshot img { border-width: 0px; }
