include. common-defines.inc

define. css ../base.css

define. style
#logo { float: left;
  }
.clearit { clear: both;
  }
h2 { width: 500px;
  }
ul#m2 { border: 1px solid black;
  float: right;
  }
block { border: 0px solid black;
  display: block;
  padding-left: 4em;
  }
.axial { border: 1px solid black; display: none;}
p.screenshot { text-align: center; }
p.screenshot img { border-width: 0px; }
