include. common-defines.inc

define. css ../base.css

define. style
#logo { float: left;
  }
.clearit { clear: both;
  }
h2 { width: 500px;
  }
ul#m2 { border: 1px solid black;
  float: right;
  }
block { border: 0px solid black;
  display: block;
  padding-left: 4em;
  }
.axial { border: 1px solid black; display: none;}
.thumbnail { 
  float: left; 
  width: 60px; 
  border: 1px solid #999; 
  margin: 0 15px 15px 0;  
  padding: 5px;
}
.clearboth { clear: both; }
p.screenshot { text-align: center; }
p.screenshot img { border-width: 0px; }
