define. fs Flying Saucer

define. css21 "CSS 2.1 Specification":http://www.w3.org/TR/CSS21/

define. OpenPDF (ex. iText) "OpenPDF":https://github.com/LibrePDF/OpenPDF

define. jlogging "java.util.logging":http://java.sun.com/j2se/1.4.2/docs/api/java/util/logging/package-summary.html

define. cssparser "CSSParser":http://cssparser.sourceforge.net/

define. mailing-list.user "mailing list":https://xhtmlrenderer.dev.java.net/servlets/ProjectMailingListList

define. mailing-list "mailing list":https://xhtmlrenderer.dev.java.net/servlets/ProjectMailingListList

define. issue-tracker "issue tracker":https://xhtmlrenderer.dev.java.net/servlets/ProjectIssues

define. guide "User's Guide":users-guide-r7rc1#.pdf
